### ISSUE TITLE
[Docker] Errors when compiling Webpack

### ISSUE THREAD

**Issue by Jesus82** [BeWelcome/rox#229]
I'm getting two errors right now when I try to run 
```
make install
npx encore dev --watch
```
First, I have to `cd public/build/ && sudo chmod -R 777 ./` in order to Webpack to work.

After that, I get 
```

 ERROR in Entry module not found: Error: Can't resolve './assets/js/index.js' in '/var/www/html/bewelcome/rox/public/build'
    
    ERROR in Entry module not found: Error: Can't resolve './assets/js/sw.js' in '/var/www/html/bewelcome/rox/public/build'
    
    ERROR in Cannot read property 'source' of undefined
```

**Comment by gboniscontro** [comment]
hello i have errors tooo
g@HP:~/rox$ make install
git rev-parse --short HEAD > VERSION
test -f docker-compose.override.yml || cp docker-compose.override.yml.dist docker-compose.override.yml
curl https://downloads.bewelcome.org/for_developers/rox_test_db/languages.sql.bz2 -o ./docker/db/languages.sql.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7681  100  7681    0     0   3333      0  0:00:02  0:00:02 --:--:--  3333
curl https://downloads.bewelcome.org/for_developers/rox_test_db/words.sql.bz2 -o ./docker/db/words.sql.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3675k  100 3675k    0     0  73937      0  0:00:50  0:00:50 --:--:-- 79143
bunzip2 --force ./docker/db/languages.sql.bz2 ./docker/db/words.sql.bz2
docker-compose up -d
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
[86755] Failed to execute script docker-compose
make: *** [Makefile:22: install] Error 255

**Comment by thisismeonmounteverest** [comment]
@gboniscontro You're doing this on which operating system?

There is a make install sudo call in case your OS insists on root rights.

**Comment by gboniscontro** [comment]
Ubuntu 20.14 dont work the steps of docker to install

**Comment by gboniscontro** [comment]
I have one error in sql connection
sudo php bin/console test:database:create --drop --force
Creating test database
======================

Dropping the database

Creating the database


In AbstractMySQLDriver.php line 112:
                                                                                                          
  An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed:   
  Temporary failure in name resolution                                                                    
                                                                                                          

In Exception.php line 18:
                                                                                                          
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolut  
  ion                                                                                                     
                                                                                                          

In PDOConnection.php line 39:
                                                                                                          
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolut  
  ion                                                                                                     
                                                                                                          

In PDOConnection.php line 39:
                                                                                                          
  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution  
                                                                                                          

test:database:create [--force] [--drop] [--translations]

**Comment by thisismeonmounteverest** [comment]
@gboniscontro You shouldn't use sudo when working within the repository.

As you probably now have a mixture of files only accessible by root and some other that are accessible for your users you either start over without sudo (preferred) or you run something like chown -R <username>:users <the folder having the code> to fix your permissions.

Docker works fine without any sudo.

The reason why the database create command fails is due to the fact that the code is prepared to easily run in Docker without changes. If you do not want to use docker you need to create a .env.local file and point it to your database server location (likely localhost instead of db).

**Comment by crumbking** [comment]
@gboniscontro As I'm working on ubuntu as well I could assist you. As @shevek already said I also running under DB_HOST=localhost in my env.local file.
But I did not use docker. Followed the manual installation instructions.

**Comment by thisismeonmounteverest** [comment]
Closing no feedback.
